# Generated by Django 4.0.5 on 2022-10-02 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post_job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=30)),
                ('company_post', models.CharField(max_length=30)),
                ('job_mode', models.CharField(max_length=30)),
                ('job_description', models.TextField(null=True)),
                ('email', models.EmailField(max_length=50)),
                ('work_hours', models.IntegerField(default=6)),
                ('country', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('from_salary', models.IntegerField(default=1000)),
                ('to_salary', models.IntegerField(default=5000)),
                ('date', models.DateTimeField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.BigIntegerField(null=True)),
                ('password', models.CharField(max_length=50)),
                ('resume', models.FileField(upload_to='file')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Applied',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('contact', models.BigIntegerField(null=True)),
                ('previous_company_name', models.CharField(max_length=100)),
                ('education', models.CharField(max_length=30)),
                ('experience', models.IntegerField(default=0)),
                ('resume', models.FileField(upload_to='file')),
                ('applied', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.post_job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
